### ISSUE TITLE
Case Creation last updated in March 2024

### ISSUE THREAD

**Issue by sporkerific** [underyx/visawhen#386]
Hello! For the NVC data, Case Creation hasn't updated since the 25th March 2024 either on the website or in the JSON file. The other NVC updates seem to be fine. Thank you!
![NVC Website Graph](https://github.com/underyx/visawhen/assets/170626653/34b148ea-efa3-43b2-96da-73281258be41)

![End of Creation JSON](https://github.com/underyx/visawhen/assets/170626653/eb372afb-3df0-4d8f-9708-cce4c22ab2cc)

**Comment by sporkerific** [comment]
@underyx for visibility since I'm not sure if you get notified from this. Thanks for creating this in the first place!

**Comment by underyx** [comment]
Thank you for reporting @sporkerific! This is now fixed and the site will have this week's data in around an hour.
