### ISSUE TITLE
Backlog counts go below zero on consulate visa charts

### ISSUE THREAD

**Issue by callofktulu** [underyx/visawhen#5]
This is happening probably because of some average calculation. In reality backlog should go as low as 0. Please check the screenshot:

![Screenshot 2021-10-27 113335](https://user-images.githubusercontent.com/5358044/139040337-87139957-a8ed-4e12-bae9-8f76e54e0707.jpg)

**Comment by underyx** [comment]
I'm closing this issue as I removed the backlog numbers yesterday. After two years of cumulative guessing they were diverging from reality too much.
